const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.video,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.solid,
		C3.Behaviors.Turret,
		C3.Behaviors.Bullet,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Pin,
		C3.Behaviors.LOS,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Tilemap,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.video.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{BotaoRecomeçar: 0},
	{GameOverFundo: 0},
	{ScoreGameOver: 0},
	{morte: 0},
	{Contagem_pontos: 0},
	{ContagemMoedas: 0},
	{Tempo: 0},
	{Coracao: 0},
	{Sprite3: 0},
	{Teclado: 0},
	{Texto: 0},
	{Toque: 0},
	{vida_extra: 0},
	{Mouse: 0},
	{Áudio: 0},
	{Vídeo: 0},
	{Vídeo2: 0},
	{tutorial: 0},
	{Pause: 0},
	{TelaPause: 0},
	{pause_brasao: 0},
	{botao_continue: 0},
	{botao_reiniciar: 0},
	{botao_sair: 0},
	{texto_pause: 0},
	{tela_pause: 0},
	{sair_do_jogo: 0},
	{Sprite: 0},
	{reiniciar_layout: 0},
	{Sprite4: 0},
	{continue: 0},
	{paused_2: 0},
	{reiniciar: 0},
	{Sólido: 0},
	{Barreira1: 0},
	{Barreira2: 0},
	{Barreira3: 0},
	{Barreira4: 0},
	{Barreira5: 0},
	{Barreira6: 0},
	{Canhão: 0},
	{Boss1: 0},
	{boss_torreta: 0},
	{BombaExplosao: 0},
	{CanhaoE: 0},
	{Projétil: 0},
	{LaserE: 0},
	{AlvoCanhaoE: 0},
	{Switch1: 0},
	{Switch2: 0},
	{Switch3: 0},
	{Switch4: 0},
	{Switch5: 0},
	{Switch6: 0},
	{Trava1: 0},
	{Trava2: 0},
	{Trava3: 0},
	{CanhaoD: 0},
	{LaserD: 0},
	{Bomba1: 0},
	{AlvoCanhaoD: 0},
	{MovimentoEmGrid2: 0},
	{caixa_boss1: 0},
	{PowerUp: 0},
	{caixa_boss2: 0},
	{boss_hp: 0},
	{SwitchBarreirasD: 0},
	{SwitchBarreirasE: 0},
	{SaidaB1: 0},
	{mar_fogo: 0},
	{mar_fogo_explosao: 0},
	{torreta: 0},
	{canhao: 0},
	{mar_de_fogo: 0},
	{botao_barreira_direita: 0},
	{botao_barreira_esquerda: 0},
	{Bomba: 0},
	{Fixar: 0},
	{alvo: 0},
	{boss_morte: 0},
	{caixa_boss3: 0},
	{caixa_boss4: 0},
	{caixa_boss5: 0},
	{caixa_boss6: 0},
	{portao: 0},
	{Movimento: 0},
	{MovimentoEmGrid: 0},
	{drone_patrulheiro: 0},
	{drone_patrulheiro_morte: 0},
	{CampoDeVisão: 0},
	{ExploradorDeRotas: 0},
	{drone_perseguidor: 0},
	{drone_perseguidor_morte: 0},
	{Caixa: 0},
	{Obstaculo: 0},
	{Parede: 0},
	{fundo_basico: 0},
	{Saida: 0},
	{"32_caixa": 0},
	{"32_Obstaculos": 0},
	{"32_Parede": 0},
	{piso_areia: 0},
	{"32_caixa_destruir": 0},
	{piso_chefe: 0},
	{piso_lixo: 0},
	{parede_chefe: 0},
	{obstaculos_concreto: 0},
	{Mosaico: 0},
	{Moeda: 0},
	{Senóide: 0},
	{galoborg: 0},
	{Hitbox: 0},
	{barra_energia: 0},
	{barra_hp: 0},
	{pontuacao: 0},
	{Player: 0},
	{PlayerBoss: 0},
	{parabens: 0},
	{Sprite2: 0},
	{botao_reiniciar_parabens: 0},
	{tela_start: 0},
	{botao_comeco: 0},
	{logo: 0},
	{id: 0},
	{bloco: 0},
	{fundo_transicao: 0},
	{Barreiras: 0},
	{BombaExplosão: 0},
	{Boss: 0},
	{SwitchsBarreiras: 0},
	{inimigos: 0},
	{Pontos: 0},
	{tempo: 0},
	{Bombas: 0},
	{Botoes: 0},
	{Torretas: 0},
	{TurnoDoBoss: 0},
	{BossHP: 0},
	{invencibilidade: 0},
	{hitbox: 0},
	{Contador_moeda_vida: 0},
	{contador_vida: 0},
	{contador_barra_vida: 0},
	{barra_hp_l: 0},
	{mudanca_fase: 0},
	{game_over: 0},
	{paused: 0}
];

self.InstanceType = {
	BotaoRecomeçar: class extends self.ISpriteInstance {},
	GameOverFundo: class extends self.ISpriteInstance {},
	ScoreGameOver: class extends self.ITextInstance {},
	morte: class extends self.IWorldInstance {},
	Contagem_pontos: class extends self.ITextInstance {},
	ContagemMoedas: class extends self.ITextInstance {},
	Tempo: class extends self.ITextInstance {},
	Coracao: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Texto: class extends self.ITextInstance {},
	Toque: class extends self.IInstance {},
	vida_extra: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Vídeo: class extends self.IWorldInstance {},
	Vídeo2: class extends self.IWorldInstance {},
	tutorial: class extends self.ISpriteInstance {},
	Pause: class extends self.ITextInstance {},
	TelaPause: class extends self.ISpriteInstance {},
	pause_brasao: class extends self.ISpriteInstance {},
	botao_continue: class extends self.ISpriteInstance {},
	botao_reiniciar: class extends self.ISpriteInstance {},
	botao_sair: class extends self.ISpriteInstance {},
	texto_pause: class extends self.ITextInstance {},
	tela_pause: class extends self.ISpriteInstance {},
	sair_do_jogo: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	reiniciar_layout: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	continue: class extends self.ISpriteInstance {},
	paused_2: class extends self.ISpriteInstance {},
	reiniciar: class extends self.ITextInstance {},
	Barreira1: class extends self.ISpriteInstance {},
	Barreira2: class extends self.ISpriteInstance {},
	Barreira3: class extends self.ISpriteInstance {},
	Barreira4: class extends self.ISpriteInstance {},
	Barreira5: class extends self.ISpriteInstance {},
	Barreira6: class extends self.ISpriteInstance {},
	Boss1: class extends self.ISpriteInstance {},
	boss_torreta: class extends self.ISpriteInstance {},
	BombaExplosao: class extends self.ISpriteInstance {},
	CanhaoE: class extends self.ISpriteInstance {},
	LaserE: class extends self.ISpriteInstance {},
	AlvoCanhaoE: class extends self.ISpriteInstance {},
	Switch1: class extends self.ISpriteInstance {},
	Switch2: class extends self.ISpriteInstance {},
	Switch3: class extends self.ISpriteInstance {},
	Switch4: class extends self.ISpriteInstance {},
	Switch5: class extends self.ISpriteInstance {},
	Switch6: class extends self.ISpriteInstance {},
	Trava1: class extends self.ISpriteInstance {},
	Trava2: class extends self.ISpriteInstance {},
	Trava3: class extends self.ISpriteInstance {},
	CanhaoD: class extends self.ISpriteInstance {},
	LaserD: class extends self.ISpriteInstance {},
	Bomba1: class extends self.ISpriteInstance {},
	AlvoCanhaoD: class extends self.ISpriteInstance {},
	caixa_boss1: class extends self.ISpriteInstance {},
	PowerUp: class extends self.ISpriteInstance {},
	caixa_boss2: class extends self.ISpriteInstance {},
	boss_hp: class extends self.ISpriteInstance {},
	SwitchBarreirasD: class extends self.ISpriteInstance {},
	SwitchBarreirasE: class extends self.ISpriteInstance {},
	SaidaB1: class extends self.ISpriteInstance {},
	mar_fogo: class extends self.ISpriteInstance {},
	mar_fogo_explosao: class extends self.ISpriteInstance {},
	torreta: class extends self.ISpriteInstance {},
	canhao: class extends self.ISpriteInstance {},
	mar_de_fogo: class extends self.ISpriteInstance {},
	botao_barreira_direita: class extends self.ISpriteInstance {},
	botao_barreira_esquerda: class extends self.ISpriteInstance {},
	Bomba: class extends self.ISpriteInstance {},
	alvo: class extends self.ISpriteInstance {},
	boss_morte: class extends self.ISpriteInstance {},
	caixa_boss3: class extends self.ISpriteInstance {},
	caixa_boss4: class extends self.ISpriteInstance {},
	caixa_boss5: class extends self.ISpriteInstance {},
	caixa_boss6: class extends self.ISpriteInstance {},
	portao: class extends self.ISpriteInstance {},
	drone_patrulheiro: class extends self.ISpriteInstance {},
	drone_patrulheiro_morte: class extends self.ISpriteInstance {},
	drone_perseguidor: class extends self.ISpriteInstance {},
	drone_perseguidor_morte: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Obstaculo: class extends self.ISpriteInstance {},
	Parede: class extends self.ISpriteInstance {},
	fundo_basico: class extends self.ISpriteInstance {},
	Saida: class extends self.ISpriteInstance {},
	_32_caixa: class extends self.ISpriteInstance {},
	_32_Obstaculos: class extends self.ITilemapInstance {},
	_32_Parede: class extends self.ITilemapInstance {},
	piso_areia: class extends self.ISpriteInstance {},
	_32_caixa_destruir: class extends self.ISpriteInstance {},
	piso_chefe: class extends self.ISpriteInstance {},
	piso_lixo: class extends self.ISpriteInstance {},
	parede_chefe: class extends self.ISpriteInstance {},
	obstaculos_concreto: class extends self.ITilemapInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Moeda: class extends self.ISpriteInstance {},
	galoborg: class extends self.ISpriteInstance {},
	Hitbox: class extends self.ISpriteInstance {},
	barra_energia: class extends self.ISpriteInstance {},
	barra_hp: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerBoss: class extends self.ISpriteInstance {},
	parabens: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	botao_reiniciar_parabens: class extends self.ISpriteInstance {},
	tela_start: class extends self.ISpriteInstance {},
	botao_comeco: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	bloco: class extends self.ISpriteInstance {},
	fundo_transicao: class extends self.ISpriteInstance {},
	Barreiras: class extends self.ISpriteInstance {},
	BombaExplosão: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	SwitchsBarreiras: class extends self.ISpriteInstance {},
	inimigos: class extends self.ISpriteInstance {}
}